// Auto-generated by update_dashboard.py v2.0. Do not edit directly.
// Last updated: 2026-06-26T06:00:00.000000Z
window.DASHBOARD_DATA = {
  "meta": {
    "schema_version": "2.0.0",
    "system_name": "Dylan Crowe Musician Business OS",
    "last_updated": "2026-06-26T06:00:00.000000Z",
    "tour_name": "One Guitar. One Dog. Every Town in Australia.",
    "tour_start": "2026-08-15",
    "tour_end": "2026-12-08",
    "tour_weeks": 16,
    "artist": {
      "name": "Dylan Crowe",
      "role": "Solo musician / touring artist",
      "companion": "Maverick (Australian Shepherd)",
      "email": "dylancrowemusic@gmail.com",
      "instagram": "@dylan_crowe_music",
      "website": "https://dylancrowemusic.github.io"
    }
  },
  "config": {
    "brand": {
      "cosmic_blue": "#1A1A3E",
      "cyan": "#00B4D8",
      "magenta": "#D946EF",
      "amber": "#D97706",
      "green": "#166534",
      "gold": "#F59E0B",
      "off_white": "#F5F0E8"
    },
    "financial_targets": {
      "net_savings_goal": 37000.0,
      "gross_income_target": 52200.0,
      "total_expenses_budget": 15200.0,
      "blended_avg_per_gig": 870.0,
      "total_appearances_target": 60
    },
    "income_streams": {
      "busking": {
        "label": "Busking",
        "color": "#166534",
        "avg_session_earnings": 300.0,
        "weekly_target_sessions": 3,
        "weekly_target_earnings": 1000.0
      },
      "venue_gig": {
        "label": "Venue Gig",
        "color": "#00B4D8",
        "avg_fee": 400.0,
        "fee_range": [
          200,
          500
        ],
        "weekly_target_gigs": 3.5,
        "weekly_target_earnings": 1400.0
      },
      "house_concert": {
        "label": "House Concert",
        "color": "#D97706",
        "avg_revenue": 700.0,
        "revenue_range": [
          500,
          1250
        ],
        "weekly_target_shows": 1,
        "weekly_target_earnings": 700.0
      }
    },
    "house_concert_tiers": {
      "starter": {
        "label": "Intimate",
        "guest_range": [
          20,
          25
        ],
        "ticket_price": 25.0,
        "early_bird_price": 20.0,
        "door_price": 30.0,
        "revenue_range": [
          500,
          625
        ],
        "host_free": true
      },
      "standard": {
        "label": "Classic",
        "guest_range": [
          25,
          35
        ],
        "ticket_price": 25.0,
        "early_bird_price": 20.0,
        "door_price": 30.0,
        "revenue_range": [
          625,
          875
        ],
        "host_free": true
      },
      "premium": {
        "label": "Big Night",
        "guest_range": [
          35,
          50
        ],
        "ticket_price": 25.0,
        "early_bird_price": 20.0,
        "door_price": 30.0,
        "revenue_range": [
          875,
          1250
        ],
        "host_free": true
      }
    },
    "venue_pipeline_stages": [
      "not_contacted",
      "called",
      "emailed",
      "follow_up_1",
      "follow_up_2",
      "booked",
      "declined",
      "played"
    ],
    "house_concert_pipeline_stages": [
      "posted",
      "interested",
      "confirmed",
      "completed",
      "cancelled"
    ],
    "tour_stop_statuses": [
      "Planned",
      "Current",
      "Completed",
      "Skipped"
    ],
    "transit_statuses": [
      "Scheduled",
      "In_Transit",
      "Arrived",
      "Departed",
      "Dreaming"
    ],
    "expense_categories": [
      "fuel",
      "accommodation",
      "food",
      "gear",
      "maverick",
      "marketing",
      "misc"
    ],
    "expense_sources": [
      "tour",
      "local"
    ],
    "facebook_groups": [
      "Perth Music Lovers",
      "Fremantle Community Board",
      "Margaret River Locals",
      "Adelaide Live Music at Home",
      "Melbourne House Concerts",
      "Sydney Acoustic Sessions",
      "Byron Bay Music Community",
      "Brisbane Live Music at Home",
      "Sunshine Coast Community"
    ]
  },
  "todos": [
    {
      "id": 1,
      "task": "Service oil",
      "completed": false,
      "is_weekly": true,
      "category": "vehicle"
    },
    {
      "id": 2,
      "task": "Fuel to parks",
      "completed": false,
      "is_weekly": false,
      "category": "ops"
    },
    {
      "id": 3,
      "task": "Organize busking cash float",
      "completed": false,
      "is_weekly": false,
      "category": "busking"
    },
    {
      "id": 4,
      "task": "Verify council permits",
      "completed": false,
      "is_weekly": true,
      "category": "busking"
    },
    {
      "id": 5,
      "task": "Post house concert invitations to Facebook groups",
      "completed": false,
      "is_weekly": false,
      "category": "house_concert"
    },
    {
      "id": 6,
      "task": "Follow up venue emails (72hr rule)",
      "completed": false,
      "is_weekly": true,
      "category": "venue"
    },
    {
      "id": 7,
      "task": "Capture reels at tonight's gig",
      "completed": false,
      "is_weekly": false,
      "category": "marketing"
    }
  ],
  "tour_stops": [
    {
      "id": 1,
      "name": "Perth",
      "state": "WA",
      "segment_type": "Major Metro",
      "est_duration_days": 7,
      "arrival_date": "2026-08-15",
      "departure_date": "2026-08-22",
      "status": "Current",
      "transit_status": "Arrived",
      "week_type": "city",
      "notes": "Metro bandrooms, Raine Square busking, breweries.",
      "targets": {
        "busking": {
          "sessions_target": 5,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1500.0
        },
        "venue_gig": {
          "gigs_target": 4,
          "venues_contacted_target": 8,
          "gigs_booked_target": 4,
          "earnings_target": 1600.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 4,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 2,
          "spots_scouted": 2,
          "spots_confirmed": 2,
          "earnings_actual": 620.0
        },
        "venue_gig": {
          "gigs_booked": 2,
          "venues_contacted": 6,
          "gigs_played": 1,
          "earnings_actual": 400.0
        },
        "house_concert": {
          "shows_confirmed": 1,
          "hosts_contacted": 3,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 3800.0,
        "actual_income": 1020.0,
        "actual_expenses": 380.0,
        "net": 640.0
      },
      "busking_spot_ids": [
        "bsk-perth-raine-sq",
        "bsk-perth-murray-st"
      ],
      "venue_ids": [
        "ven-perth-irish-rose",
        "ven-perth-moon-cafe",
        "ven-perth-velveteen"
      ],
      "house_concert_ids": [
        "hc-perth-sarah-mitchell",
        "hc-perth-james-wong"
      ],
      "marketing_id": "mkt-perth-001"
    },
    {
      "id": 2,
      "name": "Fremantle",
      "state": "WA",
      "segment_type": "Coastal Arts Hub",
      "est_duration_days": 4,
      "arrival_date": "2026-08-22",
      "departure_date": "2026-08-26",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "city",
      "notes": "Fremantle Markets, trendy late-night bars, busking.",
      "targets": {
        "busking": {
          "sessions_target": 3,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 2,
          "earnings_target": 900.0
        },
        "venue_gig": {
          "gigs_target": 3,
          "venues_contacted_target": 6,
          "gigs_booked_target": 3,
          "earnings_target": 1200.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 3,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 2800.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 3,
      "name": "Bunbury",
      "state": "WA",
      "segment_type": "Regional Hub",
      "est_duration_days": 3,
      "arrival_date": "2026-08-26",
      "departure_date": "2026-08-29",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Local taverns, South West wine bars, regional theatres.",
      "targets": {
        "busking": {
          "sessions_target": 3,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 1,
          "earnings_target": 900.0
        },
        "venue_gig": {
          "gigs_target": 2,
          "venues_contacted_target": 4,
          "gigs_booked_target": 2,
          "earnings_target": 800.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 2,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1700.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 4,
      "name": "Margaret River",
      "state": "WA",
      "segment_type": "Premium Coastal/Wine",
      "est_duration_days": 5,
      "arrival_date": "2026-08-29",
      "departure_date": "2026-09-03",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "High-paying tourist craft breweries, cellar doors.",
      "targets": {
        "busking": {
          "sessions_target": 4,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1200.0
        },
        "venue_gig": {
          "gigs_target": 4,
          "venues_contacted_target": 8,
          "gigs_booked_target": 4,
          "earnings_target": 1600.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 3,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 3500.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 5,
      "name": "Albany",
      "state": "WA",
      "segment_type": "Coastal Regional",
      "est_duration_days": 3,
      "arrival_date": "2026-09-03",
      "departure_date": "2026-09-06",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Historic pubs, Great Southern community spaces.",
      "targets": {
        "busking": {
          "sessions_target": 3,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 1,
          "earnings_target": 900.0
        },
        "venue_gig": {
          "gigs_target": 2,
          "venues_contacted_target": 4,
          "gigs_booked_target": 2,
          "earnings_target": 800.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 2,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1700.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 6,
      "name": "Esperance",
      "state": "WA",
      "segment_type": "Remote Coastal",
      "est_duration_days": 3,
      "arrival_date": "2026-09-06",
      "departure_date": "2026-09-09",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Esperance Yacht Club, regional community hub.",
      "targets": {
        "busking": {
          "sessions_target": 2,
          "spots_scouted_target": 1,
          "spots_confirmed_target": 1,
          "earnings_target": 600.0
        },
        "venue_gig": {
          "gigs_target": 1,
          "venues_contacted_target": 3,
          "gigs_booked_target": 1,
          "earnings_target": 400.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 1,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1000.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 7,
      "name": "Kalgoorlie",
      "state": "WA",
      "segment_type": "Inland Mining Hub",
      "est_duration_days": 3,
      "arrival_date": "2026-09-09",
      "departure_date": "2026-09-12",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Historic goldfields pubs, high-paying working clubs.",
      "targets": {
        "busking": {
          "sessions_target": 2,
          "spots_scouted_target": 1,
          "spots_confirmed_target": 1,
          "earnings_target": 600.0
        },
        "venue_gig": {
          "gigs_target": 2,
          "venues_contacted_target": 4,
          "gigs_booked_target": 2,
          "earnings_target": 800.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 1,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1400.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 8,
      "name": "Adelaide",
      "state": "SA",
      "segment_type": "Major Metro",
      "est_duration_days": 6,
      "arrival_date": "2026-09-16",
      "departure_date": "2026-09-22",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "city",
      "notes": "Rundle Mall high-volume busking, Grace Emily Hotel. Home base for ground ops.",
      "is_ground_ops_base": true,
      "targets": {
        "busking": {
          "sessions_target": 5,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1500.0
        },
        "venue_gig": {
          "gigs_target": 4,
          "venues_contacted_target": 8,
          "gigs_booked_target": 4,
          "earnings_target": 1600.0
        },
        "house_concert": {
          "shows_target": 2,
          "hosts_contacted_target": 5,
          "shows_confirmed_target": 2,
          "earnings_target": 1400.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 4500.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 9,
      "name": "Mount Gambier",
      "state": "SA",
      "segment_type": "Regional volcanic lake",
      "est_duration_days": 2,
      "arrival_date": "2026-09-22",
      "departure_date": "2026-09-24",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Blue Lake regional pubs, acoustic wine lounges.",
      "targets": {
        "busking": {
          "sessions_target": 2,
          "spots_scouted_target": 1,
          "spots_confirmed_target": 1,
          "earnings_target": 600.0
        },
        "venue_gig": {
          "gigs_target": 1,
          "venues_contacted_target": 3,
          "gigs_booked_target": 1,
          "earnings_target": 400.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 1,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1000.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 10,
      "name": "Warrnambool",
      "state": "VIC",
      "segment_type": "Coastal Regional",
      "est_duration_days": 2,
      "arrival_date": "2026-09-24",
      "departure_date": "2026-09-26",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Great Ocean Road coastal pubs, local arts center.",
      "targets": {
        "busking": {
          "sessions_target": 2,
          "spots_scouted_target": 1,
          "spots_confirmed_target": 1,
          "earnings_target": 600.0
        },
        "venue_gig": {
          "gigs_target": 1,
          "venues_contacted_target": 3,
          "gigs_booked_target": 1,
          "earnings_target": 400.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 1,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1000.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 11,
      "name": "Geelong/Torquay",
      "state": "VIC",
      "segment_type": "Surf Coast Gateway",
      "est_duration_days": 4,
      "arrival_date": "2026-09-26",
      "departure_date": "2026-09-30",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Surf lifesaving clubs, Torquay breweries, coastal busking.",
      "targets": {
        "busking": {
          "sessions_target": 3,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 2,
          "earnings_target": 900.0
        },
        "venue_gig": {
          "gigs_target": 3,
          "venues_contacted_target": 6,
          "gigs_booked_target": 3,
          "earnings_target": 1200.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 2,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 2800.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 12,
      "name": "Melbourne",
      "state": "VIC",
      "segment_type": "Cultural/Arts Metro",
      "est_duration_days": 8,
      "arrival_date": "2026-09-30",
      "departure_date": "2026-10-08",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "city",
      "notes": "Bourke St Mall high-traffic busking, iconic Fitzroy bandrooms.",
      "targets": {
        "busking": {
          "sessions_target": 6,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1800.0
        },
        "venue_gig": {
          "gigs_target": 5,
          "venues_contacted_target": 10,
          "gigs_booked_target": 5,
          "earnings_target": 2000.0
        },
        "house_concert": {
          "shows_target": 2,
          "hosts_contacted_target": 6,
          "shows_confirmed_target": 2,
          "earnings_target": 1400.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 5200.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 13,
      "name": "Sydney",
      "state": "NSW",
      "segment_type": "Major Metro",
      "est_duration_days": 8,
      "arrival_date": "2026-10-08",
      "departure_date": "2026-10-16",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "city",
      "notes": "Inner West pubs, Pitt St Mall busking, beachside venues.",
      "targets": {
        "busking": {
          "sessions_target": 6,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1800.0
        },
        "venue_gig": {
          "gigs_target": 5,
          "venues_contacted_target": 10,
          "gigs_booked_target": 5,
          "earnings_target": 2000.0
        },
        "house_concert": {
          "shows_target": 2,
          "hosts_contacted_target": 5,
          "shows_confirmed_target": 2,
          "earnings_target": 1400.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 5200.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 14,
      "name": "Newcastle",
      "state": "NSW",
      "segment_type": "Coastal Industrial/Arts",
      "est_duration_days": 4,
      "arrival_date": "2026-10-16",
      "departure_date": "2026-10-20",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Beachfront beer gardens, Hunter region craft breweries.",
      "targets": {
        "busking": {
          "sessions_target": 3,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 1,
          "earnings_target": 900.0
        },
        "venue_gig": {
          "gigs_target": 3,
          "venues_contacted_target": 6,
          "gigs_booked_target": 3,
          "earnings_target": 1200.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 2,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 2800.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 15,
      "name": "Port Macquarie",
      "state": "NSW",
      "segment_type": "Coastal Regional",
      "est_duration_days": 3,
      "arrival_date": "2026-10-20",
      "departure_date": "2026-10-23",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Mid North Coast taverns, tourist-heavy holiday park gigs.",
      "targets": {
        "busking": {
          "sessions_target": 3,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 1,
          "earnings_target": 900.0
        },
        "venue_gig": {
          "gigs_target": 2,
          "venues_contacted_target": 4,
          "gigs_booked_target": 2,
          "earnings_target": 800.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 1,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1700.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 16,
      "name": "Coffs Harbour",
      "state": "NSW",
      "segment_type": "Coastal Regional",
      "est_duration_days": 3,
      "arrival_date": "2026-10-23",
      "departure_date": "2026-10-26",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Solitary Islands tourist pubs, coastal clubs.",
      "targets": {
        "busking": {
          "sessions_target": 3,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 1,
          "earnings_target": 900.0
        },
        "venue_gig": {
          "gigs_target": 2,
          "venues_contacted_target": 4,
          "gigs_booked_target": 2,
          "earnings_target": 800.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 1,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1700.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 17,
      "name": "Byron Bay",
      "state": "NSW",
      "segment_type": "Legendary Busking/Hub",
      "est_duration_days": 5,
      "arrival_date": "2026-10-26",
      "departure_date": "2026-10-31",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "city",
      "notes": "Byron Great Dunny/Beachfront busking, boutique hotel lounges.",
      "targets": {
        "busking": {
          "sessions_target": 5,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1500.0
        },
        "venue_gig": {
          "gigs_target": 4,
          "venues_contacted_target": 8,
          "gigs_booked_target": 4,
          "earnings_target": 1600.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 3,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 3800.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 18,
      "name": "Brunswick Heads",
      "state": "NSW",
      "segment_type": "Boho Coastal Enclave",
      "est_duration_days": 2,
      "arrival_date": "2026-10-31",
      "departure_date": "2026-11-02",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "regional",
      "notes": "Hotel Brunswick (famous beer garden), riverside busking.",
      "targets": {
        "busking": {
          "sessions_target": 2,
          "spots_scouted_target": 1,
          "spots_confirmed_target": 1,
          "earnings_target": 600.0
        },
        "venue_gig": {
          "gigs_target": 1,
          "venues_contacted_target": 3,
          "gigs_booked_target": 1,
          "earnings_target": 400.0
        },
        "house_concert": {
          "shows_target": 0,
          "hosts_contacted_target": 1,
          "shows_confirmed_target": 0,
          "earnings_target": 0.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 1000.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 19,
      "name": "Gold Coast",
      "state": "QLD",
      "segment_type": "Beachfront/Surf",
      "est_duration_days": 5,
      "arrival_date": "2026-11-02",
      "departure_date": "2026-11-07",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "city",
      "notes": "Surf clubs, Burleigh Heads busking, high-turnover hotels.",
      "targets": {
        "busking": {
          "sessions_target": 4,
          "spots_scouted_target": 2,
          "spots_confirmed_target": 2,
          "earnings_target": 1200.0
        },
        "venue_gig": {
          "gigs_target": 3,
          "venues_contacted_target": 6,
          "gigs_booked_target": 3,
          "earnings_target": 1200.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 3,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 3100.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 20,
      "name": "Brisbane",
      "state": "QLD",
      "segment_type": "Major Metro",
      "est_duration_days": 7,
      "arrival_date": "2026-11-07",
      "departure_date": "2026-11-14",
      "status": "Planned",
      "transit_status": "Scheduled",
      "week_type": "city",
      "notes": "Queen St Mall busking, Fortitude Valley live venues.",
      "targets": {
        "busking": {
          "sessions_target": 5,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1500.0
        },
        "venue_gig": {
          "gigs_target": 4,
          "venues_contacted_target": 8,
          "gigs_booked_target": 4,
          "earnings_target": 1600.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 3,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 3800.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    },
    {
      "id": 21,
      "name": "Sunshine Coast",
      "state": "QLD",
      "segment_type": "Tour Finale",
      "est_duration_days": 6,
      "arrival_date": "2026-11-14",
      "departure_date": "2026-11-20",
      "status": "Target",
      "transit_status": "Dreaming",
      "week_type": "city",
      "notes": "Hinterland breweries, Noosa waterfront spaces, tour wrap party.",
      "targets": {
        "busking": {
          "sessions_target": 5,
          "spots_scouted_target": 3,
          "spots_confirmed_target": 2,
          "earnings_target": 1500.0
        },
        "venue_gig": {
          "gigs_target": 4,
          "venues_contacted_target": 8,
          "gigs_booked_target": 4,
          "earnings_target": 1600.0
        },
        "house_concert": {
          "shows_target": 1,
          "hosts_contacted_target": 3,
          "shows_confirmed_target": 1,
          "earnings_target": 700.0
        }
      },
      "actuals": {
        "busking": {
          "sessions_completed": 0,
          "spots_scouted": 0,
          "spots_confirmed": 0,
          "earnings_actual": 0.0
        },
        "venue_gig": {
          "gigs_booked": 0,
          "venues_contacted": 0,
          "gigs_played": 0,
          "earnings_actual": 0.0
        },
        "house_concert": {
          "shows_confirmed": 0,
          "hosts_contacted": 0,
          "shows_completed": 0,
          "earnings_actual": 0.0
        }
      },
      "financials": {
        "projected_income": 3800.0,
        "actual_income": 0.0,
        "actual_expenses": 0.0,
        "net": 0.0
      },
      "busking_spot_ids": [],
      "venue_ids": [],
      "house_concert_ids": [],
      "marketing_id": null
    }
  ],
  "busking_spots": [
    {
      "id": "bsk-perth-raine-sq",
      "tour_stop_id": 1,
      "name": "Raine Square",
      "city": "Perth",
      "address": "Raine Square, 300 Murray St, Perth WA 6000",
      "coordinates": {
        "lat": -31.9522,
        "lng": 115.8578
      },
      "foot_traffic_rating": 5,
      "permit_required": true,
      "permit_obtained": true,
      "permit_authority": "City of Perth",
      "permit_cost": 0.0,
      "best_time_of_day": "lunch_rush",
      "best_time_notes": "11:30am-2pm office workers on lunch break. High foot traffic, high tips.",
      "acoustics_notes": "Covered arcade \u2014 good natural reverb, protected from wind.",
      "earnings_history": [
        {
          "date": "2026-08-16",
          "duration_minutes": 180,
          "earnings": 320.0,
          "merch_sales": 45.0,
          "notes": "Saturday lunch rush. Played 2 hours, crowd was generous. Sold 2 CDs."
        },
        {
          "date": "2026-08-18",
          "duration_minutes": 150,
          "earnings": 180.0,
          "merch_sales": 0.0,
          "notes": "Monday, quieter than expected. Rain affected afternoon traffic."
        }
      ],
      "total_earnings_logged": 500.0,
      "total_sessions": 2,
      "avg_earnings_per_session": 250.0,
      "status": "confirmed",
      "discovered_date": "2026-08-15",
      "tags": [
        "covered",
        "high_traffic",
        "lunch_rush",
        "permit_free"
      ]
    },
    {
      "id": "bsk-perth-murray-st",
      "tour_stop_id": 1,
      "name": "Murray Street Mall",
      "city": "Perth",
      "address": "Murray Street Mall, Perth WA 6000",
      "coordinates": {
        "lat": -31.953,
        "lng": 115.859
      },
      "foot_traffic_rating": 4,
      "permit_required": true,
      "permit_obtained": true,
      "permit_authority": "City of Perth",
      "permit_cost": 0.0,
      "best_time_of_day": "afternoon",
      "best_time_notes": "2pm-5pm shoppers and tourists. Busiest Thu-Sat.",
      "acoustics_notes": "Open mall \u2014 some wind exposure. Position near Hay St entrance for shelter.",
      "earnings_history": [
        {
          "date": "2026-08-17",
          "duration_minutes": 200,
          "earnings": 120.0,
          "merch_sales": 25.0,
          "notes": "Sunday afternoon. Decent crowd but lots of competing buskers."
        }
      ],
      "total_earnings_logged": 120.0,
      "total_sessions": 1,
      "avg_earnings_per_session": 120.0,
      "status": "confirmed",
      "discovered_date": "2026-08-15",
      "tags": [
        "open_air",
        "shopping",
        "weekend_peak"
      ]
    }
  ],
  "venues": [
    {
      "id": "ven-perth-irish-rose",
      "tour_stop_id": 1,
      "name": "The Irish Rose",
      "city": "Perth",
      "state": "WA",
      "phone": "(08) 9221 1234",
      "email": "bookings@irishroseperth.com.au",
      "contact_name": "Dave O'Brien",
      "venue_type": "Irish Pub",
      "address": "101 Aberdeen St, Perth WA 6000",
      "website": "https://irishroseperth.com.au",
      "pipeline_stage": "booked",
      "stage_history": [
        {
          "stage": "not_contacted",
          "date": "2026-06-01"
        },
        {
          "stage": "called",
          "date": "2026-06-05",
          "notes": "Spoke to Dave. Interested. Send EPK."
        },
        {
          "stage": "emailed",
          "date": "2026-06-05",
          "notes": "EPK + press photos sent."
        },
        {
          "stage": "follow_up_1",
          "date": "2026-06-12",
          "notes": "Followed up. Dave said checking calendar."
        },
        {
          "stage": "booked",
          "date": "2026-06-18",
          "notes": "Confirmed! Friday 21 Aug, 8pm set."
        }
      ],
      "gig": {
        "date": "2026-08-21",
        "fee": 400.0,
        "set_times": [
          "20:00",
          "21:15"
        ],
        "set_duration_minutes": 45,
        "sound_check_time": "18:30",
        "stage_type": "small_stage",
        "pa_provided": true,
        "accommodation_offered": false,
        "rider_notes": "1 meal + 2 drinks provided. BYO merch.",
        "venue_notes": "Best spot is corner stage. Crowd gets lively after 9pm. Dave is great to work with."
      },
      "marketing": {
        "epk_sent": true,
        "epk_sent_date": "2026-06-05",
        "reels_captured": true,
        "reels_count": 3,
        "venue_posted_content": true,
        "venue_tagged_dylan": true,
        "social_posts_made": 2,
        "content_notes": "Got great footage of the Friday night crowd. Venue posted on their IG story and tagged."
      },
      "status": "booked",
      "priority": "high",
      "first_contacted_date": "2026-06-05",
      "tags": [
        "pub",
        "live_music_friendly",
        "fri_night"
      ]
    },
    {
      "id": "ven-perth-moon-cafe",
      "tour_stop_id": 1,
      "name": "Moon Caf\u00e9",
      "city": "Perth",
      "state": "WA",
      "phone": "(08) 9221 5678",
      "email": "hello@mooncafeperth.com.au",
      "contact_name": "Sophie Chen",
      "venue_type": "Caf\u00e9/Bar",
      "address": "150 James St, Northbridge WA 6003",
      "website": "https://mooncafeperth.com.au",
      "pipeline_stage": "follow_up_1",
      "stage_history": [
        {
          "stage": "not_contacted",
          "date": "2026-06-01"
        },
        {
          "stage": "called",
          "date": "2026-06-08",
          "notes": "Left voicemail with Sophie."
        },
        {
          "stage": "emailed",
          "date": "2026-06-09",
          "notes": "Sent EPK and availability."
        },
        {
          "stage": "follow_up_1",
          "date": "2026-06-16",
          "notes": "Emailed follow-up. No response yet."
        }
      ],
      "gig": null,
      "marketing": {
        "epk_sent": true,
        "epk_sent_date": "2026-06-09",
        "reels_captured": false,
        "reels_count": 0,
        "venue_posted_content": false,
        "venue_tagged_dylan": false,
        "social_posts_made": 0,
        "content_notes": ""
      },
      "status": "in_pipeline",
      "priority": "medium",
      "first_contacted_date": "2026-06-08",
      "tags": [
        "cafe",
        "northbridge",
        "weekend"
      ]
    },
    {
      "id": "ven-perth-velveteen",
      "tour_stop_id": 1,
      "name": "The Velveteen",
      "city": "Perth",
      "state": "WA",
      "phone": "(08) 9321 9012",
      "email": "bookings@velveteenperth.com.au",
      "contact_name": "Marcus Webb",
      "venue_type": "Live Music Venue",
      "address": "210 Aberdeen St, Perth WA 6000",
      "website": "https://velveteenperth.com.au",
      "pipeline_stage": "played",
      "stage_history": [
        {
          "stage": "not_contacted",
          "date": "2026-06-01"
        },
        {
          "stage": "called",
          "date": "2026-06-03",
          "notes": "Spoke to Marcus. Keen. Send EPK."
        },
        {
          "stage": "emailed",
          "date": "2026-06-03",
          "notes": "EPK sent."
        },
        {
          "stage": "booked",
          "date": "2026-06-10",
          "notes": "Confirmed for Wed 19 Aug."
        },
        {
          "stage": "played",
          "date": "2026-08-19",
          "notes": "Great gig! 60 people, good energy. Marcus wants us back."
        }
      ],
      "gig": {
        "date": "2026-08-19",
        "fee": 400.0,
        "set_times": [
          "19:30",
          "20:45"
        ],
        "set_duration_minutes": 45,
        "sound_check_time": "18:00",
        "stage_type": "raised_stage",
        "pa_provided": true,
        "accommodation_offered": false,
        "rider_notes": "Drinks tab $50. Meal provided.",
        "venue_notes": "Sound system is excellent. Stage lighting is moody \u2014 great for photos."
      },
      "marketing": {
        "epk_sent": true,
        "epk_sent_date": "2026-06-03",
        "reels_captured": true,
        "reels_count": 2,
        "venue_posted_content": true,
        "venue_tagged_dylan": true,
        "social_posts_made": 1,
        "content_notes": "Marcus posted on venue IG. Got 2 great reels \u2014 one crowd singing along."
      },
      "status": "played",
      "priority": "high",
      "first_contacted_date": "2026-06-03",
      "tags": [
        "live_venue",
        "good_sound",
        "repeat_booking"
      ]
    }
  ],
  "house_concerts": [
    {
      "id": "hc-perth-sarah-mitchell",
      "tour_stop_id": 1,
      "host_name": "Sarah Mitchell",
      "city": "Perth",
      "state": "WA",
      "host_email": "sarah.mitchell@email.com",
      "host_phone": "0401 234 567",
      "source": "Facebook group",
      "source_detail": "Perth Music Lovers",
      "pipeline_stage": "confirmed",
      "stage_history": [
        {
          "stage": "posted",
          "date": "2026-07-10",
          "notes": "Posted house concert invitation to Perth Music Lovers Facebook group."
        },
        {
          "stage": "interested",
          "date": "2026-07-14",
          "notes": "Sarah reached out via DM. Has a large living room, 25-30 friends."
        },
        {
          "stage": "confirmed",
          "date": "2026-07-20",
          "notes": "Confirmed for Tue 18 Aug. Classic tier, 25-35 guests."
        }
      ],
      "event": {
        "date": "2026-08-18",
        "tier": "standard",
        "tier_label": "Classic",
        "ticket_price": 25.0,
        "early_bird_price": 20.0,
        "door_price": 30.0,
        "tickets_sold": 28,
        "tickets_target": 30,
        "revenue_projected": 700.0,
        "revenue_actual": 0.0,
        "humanitix_link": "https://events.humanitix.com/dylan-crowe-perth-sarah",
        "set_times": [
          "19:30",
          "20:30"
        ],
        "venue_notes": "Large living room. Sarah says can fit 35 if needed. BYO drinks, potluck."
      },
      "outreach": {
        "facebook_groups_posted": [
          "Perth Music Lovers"
        ],
        "post_dates": [
          "2026-07-10"
        ],
        "follow_up_messages_sent": 1,
        "personal_messages_sent": 2,
        "referral_source": "Facebook group post"
      },
      "marketing": {
        "promo_kit_sent": true,
        "promo_kit_sent_date": "2026-07-21",
        "host_posted_socials": true,
        "reels_captured": false,
        "content_notes": "Sarah has been great at sharing the invite link. Pre-event content planned."
      },
      "status": "confirmed",
      "priority": "high",
      "first_contact_date": "2026-07-14",
      "tags": [
        "facebook_referral",
        "classic_tier",
        "weeknight"
      ]
    },
    {
      "id": "hc-perth-james-wong",
      "tour_stop_id": 1,
      "host_name": "James Wong",
      "city": "Perth",
      "state": "WA",
      "host_email": "james.wong@email.com",
      "host_phone": "0412 345 678",
      "source": "Venue referral",
      "source_detail": "Referred by Marcus at The Velveteen",
      "pipeline_stage": "interested",
      "stage_history": [
        {
          "stage": "posted",
          "date": "2026-07-15",
          "notes": "Marcus at The Velveteen mentioned James might host. Reached out."
        },
        {
          "stage": "interested",
          "date": "2026-07-22",
          "notes": "James responded. Interested but checking dates. Has outdoor deck space."
        }
      ],
      "event": null,
      "outreach": {
        "facebook_groups_posted": [],
        "post_dates": [],
        "follow_up_messages_sent": 1,
        "personal_messages_sent": 1,
        "referral_source": "Venue referral (Marcus @ The Velveteen)"
      },
      "marketing": {
        "promo_kit_sent": false,
        "promo_kit_sent_date": null,
        "host_posted_socials": false,
        "reels_captured": false,
        "content_notes": ""
      },
      "status": "in_pipeline",
      "priority": "medium",
      "first_contact_date": "2026-07-15",
      "tags": [
        "venue_referral",
        "outdoor_space",
        "potential_premium"
      ]
    }
  ],
  "financials": {
    "tour": {
      "target": 37000.0,
      "gross_target": 52200.0,
      "expense_budget": 15200.0,
      "current_earnings": 1020.0,
      "expenses_by_category": {
        "fuel": 350.0,
        "accommodation": 0.0,
        "food": 0.0,
        "gear": 120.0,
        "maverick": 0.0,
        "marketing": 0.0,
        "misc": 0.0
      },
      "total_expenses": 470.0,
      "net_earnings": 550.0,
      "progress_to_target_pct": 1.49,
      "income_by_stream": {
        "busking": 620.0,
        "venue_gig": 400.0,
        "house_concert": 0.0,
        "merch": 70.0
      }
    },
    "expense_budget_breakdown": {
      "fuel": 6500.0,
      "accommodation": 3500.0,
      "food": 3000.0,
      "gear": 1500.0,
      "marketing": 700.0,
      "maverick": 0.0,
      "misc": 0.0,
      "total": 15200.0
    }
  },
  "ground_ops": {
    "base_city": "Adelaide",
    "description": "Adelaide local busking float \u2014 separate from tour savings. Funds day-to-day ops when passing through Adelaide.",
    "local_busking_earnings": 0.0,
    "expenses": 0.0,
    "cash_float": 0.0,
    "operational_bank": 0.0,
    "transaction_history": []
  },
  "marketing": [
    {
      "id": "mkt-perth-001",
      "tour_stop_id": 1,
      "city": "Perth",
      "content_captured": {
        "photos": 15,
        "reels": 5,
        "videos": 2,
        "live_recordings": 1
      },
      "social_posts": [
        {
          "platform": "instagram",
          "post_type": "reel",
          "date": "2026-08-16",
          "description": "Busking at Raine Square \u2014 crowd singing along to 'Wanderin' Man'",
          "views": 1200,
          "engagement_rate": 8.5
        },
        {
          "platform": "instagram",
          "post_type": "story",
          "date": "2026-08-19",
          "description": "The Velveteen gig \u2014 backstage + crowd shots",
          "views": 850,
          "engagement_rate": 7.2
        },
        {
          "platform": "facebook",
          "post_type": "post",
          "date": "2026-08-20",
          "description": "Thank you Perth! 2 gigs down, house concert Tuesday.",
          "views": 430,
          "engagement_rate": 12.0
        }
      ],
      "venue_collaboration": [
        {
          "venue_id": "ven-perth-velveteen",
          "venue_posted": true,
          "platform": "instagram_story",
          "tagged_dylan": true,
          "date": "2026-08-19"
        },
        {
          "venue_id": "ven-perth-irish-rose",
          "venue_posted": true,
          "platform": "instagram_post",
          "tagged_dylan": true,
          "date": "2026-08-21"
        }
      ],
      "epk_sent_to_venues": [
        "ven-perth-irish-rose",
        "ven-perth-moon-cafe",
        "ven-perth-velveteen"
      ],
      "content_summary": "Strong content from Perth. 3 venues posted and tagged. Raine Square busking reel performing well.",
      "next_actions": [
        "Edit Velveteen gig footage into highlight reel",
        "Post house concert teaser for Tuesday",
        "Send thank-you DMs to venues that posted"
      ]
    }
  ],
  "income_history": [
    {
      "id": "inc-001",
      "type": "busking",
      "amount": 320.0,
      "location": "Perth",
      "busking_spot_id": "bsk-perth-raine-sq",
      "tour_stop_id": 1,
      "description": "Saturday lunch rush at Raine Square",
      "date": "2026-08-16T14:00:00Z",
      "source": "tour"
    },
    {
      "id": "inc-002",
      "amount": 45.0,
      "type": "merch",
      "location": "Perth",
      "busking_spot_id": "bsk-perth-raine-sq",
      "tour_stop_id": 1,
      "description": "2 CDs sold at Raine Square busking session",
      "date": "2026-08-16T14:30:00Z",
      "source": "tour"
    },
    {
      "id": "inc-003",
      "type": "busking",
      "amount": 120.0,
      "location": "Perth",
      "busking_spot_id": "bsk-perth-murray-st",
      "tour_stop_id": 1,
      "description": "Sunday afternoon at Murray St Mall",
      "date": "2026-08-17T16:00:00Z",
      "source": "tour"
    },
    {
      "id": "inc-004",
      "amount": 25.0,
      "type": "merch",
      "location": "Perth",
      "busking_spot_id": "bsk-perth-murray-st",
      "tour_stop_id": 1,
      "description": "1 CD sold at Murray St",
      "date": "2026-08-17T16:15:00Z",
      "source": "tour"
    },
    {
      "id": "inc-005",
      "type": "venue_gig",
      "amount": 400.0,
      "location": "Perth",
      "venue_id": "ven-perth-velveteen",
      "tour_stop_id": 1,
      "description": "The Velveteen \u2014 Wed 19 Aug, 2 sets",
      "date": "2026-08-19T21:00:00Z",
      "source": "tour"
    },
    {
      "id": "inc-006",
      "type": "busking",
      "amount": 180.0,
      "location": "Perth",
      "busking_spot_id": "bsk-perth-raine-sq",
      "tour_stop_id": 1,
      "description": "Monday session, rain affected traffic",
      "date": "2026-08-18T13:00:00Z",
      "source": "tour"
    }
  ],
  "expense_history": [
    {
      "id": "exp-001",
      "category": "fuel",
      "amount": 350.0,
      "location": "Perth",
      "tour_stop_id": 1,
      "description": "Initial fuel fill-up for tour start",
      "source": "tour",
      "date": "2026-08-15T08:00:00Z"
    },
    {
      "id": "exp-002",
      "category": "gear",
      "amount": 120.0,
      "location": "Perth",
      "tour_stop_id": 1,
      "description": "New guitar strings, capo, patch cable",
      "source": "tour",
      "date": "2026-08-16T10:00:00Z"
    }
  ],
  "booking_summary": {
    "venues_mapped": 85,
    "venues_in_database": 3,
    "status": "85+ venues mapped across call sheets. 3 active in pipeline.",
    "pipeline_counts": {
      "not_contacted": 0,
      "called": 0,
      "emailed": 0,
      "follow_up_1": 1,
      "follow_up_2": 0,
      "booked": 1,
      "declined": 0,
      "played": 1
    }
  },
  "migration_notes": {
    "schema_version_from": "1.0.0",
    "schema_version_to": "2.0.0",
    "migration_date": "2026-06-26",
    "field_mappings": [
      {
        "old_path": "financials.target",
        "new_path": "financials.tour.target",
        "notes": "Moved under tour sub-object. Same value ($37,000)."
      },
      {
        "old_path": "financials.current_earnings",
        "new_path": "financials.tour.current_earnings",
        "notes": "Moved under tour sub-object."
      },
      {
        "old_path": "financials.fuel_expenses",
        "new_path": "financials.tour.expenses_by_category.fuel",
        "notes": "Now part of categorized expense breakdown."
      },
      {
        "old_path": "financials.gear_expenses",
        "new_path": "financials.tour.expenses_by_category.gear",
        "notes": "Now part of categorized expense breakdown."
      },
      {
        "old_path": "financials.other_expenses",
        "new_path": "financials.tour.expenses_by_category.misc",
        "notes": "Old 'other' bucket split into accommodation, food, maverick, marketing, misc."
      },
      {
        "old_path": "financials.net_earnings",
        "new_path": "financials.tour.net_earnings",
        "notes": "Now auto-calculated: current_earnings - total_expenses."
      },
      {
        "old_path": "tour_stops[].gigs_target",
        "new_path": "tour_stops[].targets.venue_gig.gigs_target",
        "notes": "Single gigs_target replaced by per-stream targets object."
      },
      {
        "old_path": "tour_stops[].gigs_booked",
        "new_path": "tour_stops[].actuals.venue_gig.gigs_booked",
        "notes": "Single gigs_booked replaced by per-stream actuals object."
      },
      {
        "old_path": "booking.venues_mapped",
        "new_path": "booking_summary.venues_mapped",
        "notes": "Renamed for clarity. Individual venues now in venues[] array."
      },
      {
        "old_path": "income_history[].type",
        "new_path": "income_history[].type",
        "notes": "Expanded choices: busking, venue_gig, house_concert, merch. Old 'gig' \u2192 'venue_gig', 'tour-busking'/'busking' \u2192 'busking', 'local-busking' stays as source='local'."
      },
      {
        "old_path": "income_history[] (no source)",
        "new_path": "income_history[].source",
        "notes": "New field: 'tour' or 'local'. Replaces the implicit Adelaide location check."
      },
      {
        "old_path": "expense_history[].category (fuel/food/gear/dog/other)",
        "new_path": "expense_history[].category",
        "notes": "Expanded: fuel, accommodation, food, gear, maverick, marketing, misc. Old 'dog' \u2192 'maverick'."
      },
      {
        "old_path": "todos[] (no category)",
        "new_path": "todos[].category",
        "notes": "New optional field: vehicle, ops, busking, venue, house_concert, marketing."
      }
    ],
    "new_entities": [
      {
        "entity": "busking_spots[]",
        "description": "Dynamically discovered busking locations with coordinates, permits, earnings history.",
        "linked_from": "tour_stops[].busking_spot_ids"
      },
      {
        "entity": "venues[]",
        "description": "CRM-lite venue booking pipeline with stage tracking and gig details.",
        "linked_from": "tour_stops[].venue_ids"
      },
      {
        "entity": "house_concerts[]",
        "description": "House concert host flywheel with pipeline stages, event details, and outreach tracking.",
        "linked_from": "tour_stops[].house_concert_ids"
      },
      {
        "entity": "marketing[]",
        "description": "Per-stop content and social media tracking with venue collaboration status.",
        "linked_from": "tour_stops[].marketing_id"
      },
      {
        "entity": "config",
        "description": "Centralized configuration for brand colors, financial targets, pricing tiers, pipeline stages, and Facebook groups."
      },
      {
        "entity": "meta",
        "description": "Schema versioning and artist/tour metadata."
      }
    ],
    "data_preservation": [
      "21-stop tour route preserved exactly (Perth \u2192 Sunshine Coast)",
      "Original todos preserved with new optional category field",
      "Income splitting logic preserved: source='tour' \u2192 financials.tour, source='local' \u2192 ground_ops",
      "Ground ops structure preserved with added transaction_history",
      "Adelaide remains the ground_ops base (is_ground_ops_base: true on stop 8)",
      "85+ venue count preserved in booking_summary.venues_mapped",
      "House concert tiers mapped: Intimate\u2192starter, Classic\u2192standard, Big Night\u2192premium"
    ]
  }
};
