/**
 * todo_list.js — Todo list with priority groups (v4 UI)
 * renderTodoList(todos) returns DOM list.
 * Groups by priority (high first). Each item: checkbox, title,
 * "AUTO" badge if auto-generated, due date, linked entity chip
 * (clickable → opens card). Inline edit. Import crud, card, badge, modal.
 *
 * @module components/todo_list
 */
import { h } from '../utils/dom.js?v=4';
import * as crud from '../crud.js?v=4';
import { renderCard } from './card.js?v=4';
import { renderBadge } from './badge.js?v=4';
import { openModal } from './modal.js?v=4';

const PRIORITY_ORDER = ['high', 'medium', 'low'];
const PRIORITY_LABEL = { high: 'High', medium: 'Medium', low: 'Low' };

function _priorityRank(p) {
  const idx = PRIORITY_ORDER.indexOf((p || '').toLowerCase());
  return idx === -1 ? PRIORITY_ORDER.length : idx;
}

function _fmtDue(due) {
  if (!due) return '';
  try {
    const d = due instanceof Date ? due : new Date(due);
    if (isNaN(d.getTime())) return String(due);
    const today = new Date(); today.setHours(0,0,0,0);
    const target = new Date(d); target.setHours(0,0,0,0);
    const diff = Math.round((target - today) / 86400000);
    if (diff === 0) return 'Today';
    if (diff === 1) return 'Tomorrow';
    if (diff === -1) return 'Yesterday';
    if (diff < 0) return `${Math.abs(diff)}d overdue`;
    if (diff < 7) return `In ${diff}d`;
    return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
  } catch (_) { return String(due); }
}

function _isOverdue(due, done) {
  if (!due || done) return false;
  try {
    const d = due instanceof Date ? due : new Date(due);
    const today = new Date(); today.setHours(0,0,0,0);
    return d < today;
  } catch (_) { return false; }
}

function _linkedChip(todo) {
  if (!todo.linkedEntityType && !todo.entityType) return null;
  const et = todo.linkedEntityType || todo.entityType;
  const eid = todo.linkedEntityId || todo.entityId;
  if (!et || !eid) return null;
  return h('button', {
    type: 'button',
    class: 'todo-link-chip',
    title: `Open ${et}`,
    onClick: (e) => {
      e.stopPropagation();
      try {
        const card = renderCard(et, eid);
        openModal(card);
      } catch (_) {}
    },
    style: {
      minHeight: '44px',
      padding: '4px 10px',
      fontSize: '11px',
      color: 'var(--brand-accent, #00d4c8)',
      background: 'rgba(0,212,200,.08)',
      border: '1px solid rgba(0,212,200,.25)',
      borderRadius: '999px',
      cursor: 'pointer',
    },
  }, '🔗 ' + et);
}

function _todoRow(todo, listEl) {
  const done = !!todo.done || !!todo.completed;
  const overdue = _isOverdue(todo.due, done);

  // Checkbox
  const checkbox = h('input', {
    type: 'checkbox',
    checked: done,
    'aria-label': 'Mark complete',
    onChange: (ev) => {
      const checked = ev.target.checked;
      if (crud.update) {
        crud.update('todos', todo.id, { done: checked, completed: checked });
      }
      // live visual update
      titleEl.style.textDecoration = checked ? 'line-through' : 'none';
      titleEl.style.opacity = checked ? '.55' : '1';
    },
    style: { width: '20px', height: '20px', minHeight: '44px', minWidth: '44px', flex: '0 0 auto', marginTop: '2px' },
  });

  // Title (inline-editable)
  const titleEl = h('div', {
    class: 'todo-title',
    tabindex: '0',
    role: 'textbox',
    'aria-multiline': 'false',
    contentEditable: 'true',
    style: {
      fontSize: '14px',
      color: 'var(--text, #f1f1f5)',
      textDecoration: done ? 'line-through' : 'none',
      opacity: done ? '.55' : '1',
      outline: 'none',
      cursor: 'text',
      flex: '1 1 auto',
      minWidth: '0',
      wordBreak: 'break-word',
      padding: '4px 6px',
      borderRadius: '4px',
      minHeight: '44px',
      display: 'flex',
      alignItems: 'center',
    },
    onBlur: (ev) => {
      const newText = ev.target.textContent.trim();
      if (newText && newText !== todo.title) {
        if (crud.update) crud.update('todos', todo.id, { title: newText });
        todo.title = newText;
      } else if (!newText) {
        ev.target.textContent = todo.title; // restore if emptied
      }
    },
    onKeyDown: (ev) => {
      if (ev.key === 'Enter') { ev.preventDefault(); ev.target.blur(); }
      if (ev.key === 'Escape') { ev.target.textContent = todo.title; ev.target.blur(); }
    },
  }, todo.title || 'Untitled');

  // Right meta cluster
  const meta = [];
  if (todo.auto || todo.autoGenerated) meta.push(renderBadge('auto'));
  if (todo.due) meta.push(h('span', {
    style: {
      fontSize: '11px',
      color: overdue ? '#eb5757' : 'var(--text-muted, #9a9aa5)',
      whiteSpace: 'nowrap',
    },
  }, '📅 ' + _fmtDue(todo.due)));
  const chip = _linkedChip(todo);
  if (chip) meta.push(chip);

  const metaWrap = h('div', {
    style: { display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap', flexShrink: '0' },
  }, meta);

  const row = h('div', {
    class: 'todo-row',
    'data-id': todo.id,
    'data-priority': (todo.priority || 'medium').toLowerCase(),
    style: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: '8px',
      padding: '10px 8px',
      borderBottom: '1px solid var(--border, #222230)',
      minHeight: '44px',
    },
  }, [checkbox, titleEl, metaWrap]);

  return row;
}

function _group(todos) {
  const groups = { high: [], medium: [], low: [], none: [] };
  (todos || []).forEach(t => {
    const p = (t.priority || '').toLowerCase();
    if (groups[p]) groups[p].push(t); else groups.none.push(t);
  });
  // sort each group: incomplete first, then by due date asc
  const sortByDue = (a, b) => {
    const ad = a.due ? new Date(a.due).getTime() || 0 : Infinity;
    const bd = b.due ? new Date(b.due).getTime() || 0 : Infinity;
    return ad - bd;
  };
  Object.keys(groups).forEach(k => {
    groups[k].sort((a, b) => {
      const ad = a.done || a.completed ? 1 : 0;
      const bd = b.done || b.completed ? 1 : 0;
      if (ad !== bd) return ad - bd;
      return sortByDue(a, b);
    });
  });
  return groups;
}

/**
 * @param {Array} todos
 * @returns {HTMLElement} todo list root
 */
export function renderTodoList(todos) {
  const groups = _group(todos);
  const order = [...PRIORITY_ORDER, 'none'];

  const sections = order
    .filter(k => groups[k] && groups[k].length > 0)
    .map(k => {
      const rows = groups[k].map(t => _todoRow(t));
      return h('section', {
        class: 'todo-group',
        'data-priority': k,
        style: { marginBottom: '16px' },
      }, [
        h('div', {
          class: 'todo-group-header',
          style: {
            fontSize: '12px',
            fontWeight: '600',
            color: 'var(--text-muted, #9a9aa5)',
            textTransform: 'uppercase',
            letterSpacing: '.05em',
            padding: '6px 8px',
            borderBottom: '1px solid var(--border, #222230)',
          },
        }, `${PRIORITY_LABEL[k] || 'Other'} · ${rows.length}`),
        h('div', { class: 'todo-group-items' }, rows),
      ]);
    });

  if (sections.length === 0) {
    sections.push(h('div', {
      style: { padding: '32px 16px', textAlign: 'center', color: 'var(--text-muted, #7a7a85)', fontSize: '13px' },
    }, 'No todos yet.'));
  }

  return h('div', {
    class: 'todo-list',
    style: { width: '100%' },
  }, sections);
}

export default renderTodoList;
